"""initial database migration

Revision ID: 2064b0200186
Revises: a6d020de9fb0
Create Date: 2020-03-12 17:07:42.040000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2064b0200186'
down_revision = 'a6d020de9fb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('adminId', sa.String(length=9), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('type', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('adminId')
    )
    op.create_table('agency',
    sa.Column('idAgency', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('type', sa.String(length=45), nullable=True),
    sa.Column('description', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('idAgency')
    )
    op.create_table('authtable',
    sa.Column('bannerId', sa.String(length=9), nullable=False),
    sa.Column('password', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('bannerId')
    )
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('student',
    sa.Column('bannerId', sa.String(length=9), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('program', sa.String(length=45), nullable=False),
    sa.Column('year', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('bannerId')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('categories',
    sa.Column('idAgency', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=45), nullable=False),
    sa.ForeignKeyConstraint(['idAgency'], [u'agency.idAgency'], )
    )
    op.create_index(op.f('ix_categories_idAgency'), 'categories', ['idAgency'], unique=False)
    op.create_table('job',
    sa.Column('idJob', sa.Integer(), nullable=False),
    sa.Column('idAgency', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('description', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['idAgency'], [u'agency.idAgency'], ),
    sa.PrimaryKeyConstraint('idJob')
    )
    op.create_index(op.f('ix_job_idAgency'), 'job', ['idAgency'], unique=False)
    op.create_table('location',
    sa.Column('City', sa.String(length=45), nullable=False),
    sa.Column('Province', sa.String(length=45), nullable=False),
    sa.Column('Address', sa.String(length=45), nullable=False),
    sa.Column('idAgency', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idAgency'], [u'agency.idAgency'], )
    )
    op.create_index(op.f('ix_location_idAgency'), 'location', ['idAgency'], unique=False)
    op.create_table('studentinterests',
    sa.Column('bannerId', sa.String(length=9), nullable=False),
    sa.Column('interest', sa.String(length=45), nullable=False),
    sa.ForeignKeyConstraint(['bannerId'], [u'student.bannerId'], )
    )
    op.create_index(op.f('ix_studentinterests_bannerId'), 'studentinterests', ['bannerId'], unique=False)
    op.create_table('studentsupp',
    sa.Column('bannerId', sa.String(length=9), nullable=False),
    sa.Column('cgpa', sa.String(length=45), nullable=True),
    sa.Column('criminalCheck', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['bannerId'], [u'student.bannerId'], ),
    sa.PrimaryKeyConstraint('bannerId')
    )
    op.create_table('applicationprocedure',
    sa.Column('idJob', sa.Integer(), nullable=False),
    sa.Column('website', sa.String(length=45), nullable=True),
    sa.Column('contactDirect', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['idJob'], [u'job.idJob'], ),
    sa.PrimaryKeyConstraint('idJob')
    )
    op.create_table('supervisor',
    sa.Column('idSupervisor', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('idJob', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['idJob'], [u'job.idJob'], ),
    sa.PrimaryKeyConstraint('idSupervisor')
    )
    op.create_index(op.f('ix_supervisor_idJob'), 'supervisor', ['idJob'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supervisor_idJob'), table_name='supervisor')
    op.drop_table('supervisor')
    op.drop_table('applicationprocedure')
    op.drop_table('studentsupp')
    op.drop_index(op.f('ix_studentinterests_bannerId'), table_name='studentinterests')
    op.drop_table('studentinterests')
    op.drop_index(op.f('ix_location_idAgency'), table_name='location')
    op.drop_table('location')
    op.drop_index(op.f('ix_job_idAgency'), table_name='job')
    op.drop_table('job')
    op.drop_index(op.f('ix_categories_idAgency'), table_name='categories')
    op.drop_table('categories')
    op.drop_table('user')
    op.drop_table('student')
    op.drop_table('blacklist_tokens')
    op.drop_table('authtable')
    op.drop_table('agency')
    op.drop_table('admin')
    # ### end Alembic commands ###
