"""initial daaatabase migration

Revision ID: 53745de6bcdc
Revises: 2064b0200186
Create Date: 2020-03-12 18:19:15.575000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53745de6bcdc'
down_revision = '2064b0200186'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('bannerId', sa.String(length=9), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('program', sa.String(length=45), nullable=False),
    sa.Column('year', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('bannerId')
    )
    op.add_column(u'user', sa.Column('activated', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'user', 'activated')
    op.drop_table('student')
    # ### end Alembic commands ###
